<?php

declare(strict_types=1);

return [
    'location_freshness_minutes' => 5,
    'available_events' => [
        'account_created',
        'account_deleted',
        'account_force_deleted',
        'account_restored',
        'account_role_created',
        'account_role_deleted',
        'account_role_force_deleted',
        'account_role_restored',
        'account_role_updated',
        'account_updated',
        'account_user_created',
        'account_user_credential_added',
        'account_user_credential_removed',
        'account_user_deleted',
        'account_user_updated',
        'anonymous_identity_created',
        'app_domain_added',
        'app_domain_removed',
        'auth_login_succeeded',
        'auth_logout',
        'auth_password_registered',
        'auth_password_reset',
        'auth_password_token_generated',
        'domain_created',
        'domain_deleted',
        'domain_force_deleted',
        'domain_restored',
        'invite_received',
        'profile_email_added',
        'profile_email_removed',
        'profile_password_updated',
        'profile_phone_added',
        'profile_phone_removed',
        'profile_updated',
        'tenant_branding_updated',
        'tenant_role_created',
        'tenant_role_deleted',
        'tenant_role_force_deleted',
        'tenant_role_restored',
        'tenant_role_updated',
        'tenant_user_deleted',
        'tenant_user_force_deleted',
        'tenant_user_managed',
        'tenant_user_restored',
    ],
    'queue' => [
        'name' => 'default',
        'tries' => 5,
        'backoff_seconds' => [5, 15, 30, 60],
    ],
];
